# Generated by Django 5.1.3 on 2024-11-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pruebas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Torneo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("fecha", models.DateTimeField()),
                ("lugar", models.CharField(max_length=200)),
                (
                    "pruebas",
                    models.ManyToManyField(
                        blank=True, related_name="torneos", to="pruebas.prueba"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AsignacionJuez",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prueba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="pruebas.prueba",
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="torneos.torneo",
                    ),
                ),
            ],
        ),
    ]
