# Generated by Django 5.1.3 on 2024-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre oficial de la prueba (e.g., Suelo, Viga de equilibrio)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada de la prueba, incluyendo reglas generales",
                        null=True,
                    ),
                ),
                (
                    "duracion_maxima",
                    models.PositiveIntegerField(
                        default=0, help_text="Duración máxima permitida en segundos"
                    ),
                ),
                (
                    "nivel_dificultad",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                        ],
                        default="medio",
                        help_text="Nivel de dificultad asignado a la prueba según la FIG",
                        max_length=50,
                    ),
                ),
                (
                    "puntaje_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Puntaje base asignado a la prueba según el código de puntuación",
                        max_digits=5,
                    ),
                ),
                (
                    "deduccion_caida",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Puntos que se restan por una caída",
                        max_digits=4,
                    ),
                ),
                (
                    "deduccion_ejecucion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="Deducción por cada error técnico o de ejecución",
                        max_digits=4,
                    ),
                ),
                (
                    "deduccion_tiempo_excedido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.1,
                        help_text="Penalización por exceder el tiempo permitido (por segundo)",
                        max_digits=4,
                    ),
                ),
                (
                    "imagen_referencia",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen ilustrativa de la prueba o el aparato",
                        null=True,
                        upload_to="imagenes_pruebas/",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(default="1990-01-01T00:00:00")),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prueba",
                "verbose_name_plural": "Pruebas",
                "ordering": ["nombre"],
            },
        ),
    ]
